//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testee
{
    using System;
    using System.Collections.Generic;
    
    public partial class local
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> nivelRec { get; set; }
        public string urlGif { get; set; }
    
        public virtual vocacoes vocacoes { get; set; }
    }
}
