//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testee
{
    using System;
    using System.Collections.Generic;
    
    public partial class vocacoes
    {
        public int id { get; set; }
        public Nullable<bool> druid { get; set; }
        public Nullable<bool> paladin { get; set; }
        public Nullable<bool> knight { get; set; }
        public Nullable<bool> sorcerer { get; set; }
    
        public virtual local local { get; set; }
    }
}
